global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Rule files specifies a list of globs. Rules and alerts are read from
# all matching files.
rule_files:
  - /etc/prometheus/rules.yml
  - rules/*.yml

scrape_configs:

  # Job para coletar as métricas de outras organizações.
  # Inclua aqui os alvos das outras organizações (Prometheus expostos).
  - job_name: rbb-federado
    honor_labels: false
    metrics_path: '/federate'
    scheme: https
    tls_config:                                          # Configurações de TLS para comunicação segura
      cert_file: /etc/prometheus/certs/certificado.crt   # Caminho para o certificado
      key_file: /etc/prometheus/certs/chave-privada.key  # Caminho para a chave privada
      insecure_skip_verify: true                         # Ignora a verificação do certificado
    params:
      'match[]':
        - '{job="rbb"}'
    static_configs:
      - targets: [ '200.152.489.10:8443']       #Prometheus DILI
        labels:
          organization: 'DILI'
      - targets: [ '36.95.2.165:8443' ]       # Prometheus CPqD
        labels:
          organization: 'CPqD'

    metric_relabel_configs:
    - source_labels: ["exported_instance"]
      target_label: "instance"
    - source_labels: ["exported_organization"]
      target_label: "organization"
    - action: "labeldrop"
      regex: "^exported_.*"
