groups:
- name: basic
  rules:

  - alert: InstanceDown
    expr: up == 0
    for: 10m
    labels:
      severity: critical
      service_status: inactive
    annotations:
      summary: "Instance [{{$labels.instance}}] down"
      description: "[{{$labels.instance}}] of job [{{$labels.job}}] has been down for more than 10 minute."
  
